pipeline {
    agent any
   
    stages {
        stage('Set up') {
            steps {
                // Définir le chemin d'accès à Maven
                sh 'export PATH=$PATH:/opt/apache-maven-3.6.3/bin'
            }
        }
        stage('Build') {
            steps {
sh '/opt/apache-maven-3.6.3/bin/mvn -B -DskipTests clean package'            }
        }
        stage('Test') {
            steps {
               sh '/opt/apache-maven-3.6.3/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
             steps {
        script {
          def componentsPath = 'build'
          def nexusUrl = 'http://localhost:8081'
          def nexusUsername = 'exosdata'
          def nexusPassword = 'stage'
          def nexusRepository = 'ExosData'
          
          sh "curl -u ${nexusUsername}:${nexusPassword} --upload-file ${componentsPath} ${nexusUrl}/repository/${nexusRepository}"
        }
      }
        }
    }
}
