pipeline {
    agent any
   
    stages {
        stage('Set up') {
            steps {
                // Définir le chemin d'accès à Maven
                sh 'export PATH=$PATH:/opt/apache-maven-3.6.3/bin'
            }
        }
        stage('Build') {
            steps {
sh '/opt/apache-maven-3.6.3/bin/mvn -B -DskipTests clean compile'            }
        }
        stage('Test') {
            steps {
               sh '/opt/apache-maven-3.6.3/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh '/opt/apache-maven-3.6.3/bin/mvn package'
            }
        }
    }
}
